# -*- coding: utf-8 -*-
import re
import string

dictionary = {
        'A': u'ア',
        'I': u'イ',
        'U': u'ウ',
        'E': u'エ',
        'O': u'オ',
        'KA':u'カ',
        'KI':u'キ',
        'KU':u'ク',
        'KE':u'ケ',
        'KO':u'コ',
        'SA':u'サ',
        'SI':u'シ',
        'SU':u'ス',
        'SE':u'セ',
        'SO':u'ソ',
        'TA':u'タ',
        'TI':u'チ',
        'TU':u'ツ',
        'TE':u'テ',
        'TO':u'ト',
        'NA':u'ナ',
        'NI':u'ニ',
        'NU':u'ヌ',
        'NE':u'ネ',
        'NO':u'ノ',
        'HA':u'ハ',
        'HI':u'ヒ',
        'HU':u'フ',
        'HE':u'ヘ',
        'HO':u'ホ',
        'MA':u'マ',
        'MI':u'ミ',
        'MU':u'ム',
        'ME':u'メ',
        'MO':u'モ',
        'YA':u'ヤ',
        'YU':u'ユ',
        'YO':u'ヨ',
        'RA':u'ラ',
        'RI':u'リ',
        'RU':u'ル',
        'RE':u'レ',
        'RO':u'ロ',
        'WA':u'ワ',
        'WO':u'ヲ',
        'GA':u'ガ',
        'GI':u'ギ',
        'GU':u'グ',
        'GE':u'ゲ',
        'GO':u'ゴ',
        'ZA':u'ザ',
        'ZI':u'ジ',
        'ZU':u'ズ',
        'ZE':u'ゼ',
        'ZO':u'ゾ',
        'DA':u'ダ',
        'DI':u'ヂ',
        'DU':u'ヅ',
        'DE':u'デ',
        'DO':u'ド',
        'BA':u'バ',
        'BI':u'ビ',
        'BU':u'ブ',
        'BE':u'ベ',
        'BO':u'ボ',
        'PA':u'パ',
        'PI':u'ピ',
        'PU':u'プ',
        'PE':u'ぺ',
        'PO':u'ポ',
        'VA':u'ヴァ',
        'VI':u'ヴィ',
        'VU':u'ヴ',
        'VE':u'ヴェ',
        'VO':u'ヴォ',
        'N' :u'ン',
        '-' :u'ー',
        }

def r2k(w):
    w = re.sub('|'.join(dictionary.keys()),lambda x: dictionary[x.group(0)],w)
    w = w.replace('$','')
    return w
